---
title: "FC"
author: "EA"
date: "15 August 2016"
output: 
    html_document:
        toc: true
---

<style type="text/css">
body, td{
  font-family: Cambria;
}
code.r{
  font-family: Inconsolata;
}
</style>


# Preparing the data
```{r}
### Notes
# install.packages('ggplot2',dependencies = T)
# Test code line with command+enter
# update.packages(checkBuilt = T,ask = F)
# head(ds) # first few lines of a dataframe
# str(ds) #show structure of dataframe
###

# Setting variables:
options(width=108)
outT <- 2.5 # Outlier factor

# Loading libraries
library(ggplot2) # for plotting
library(plyr)

#Importing the data
#data_dir <- '/Volumes/PK/'
homeDir <- path.expand('~/..')
dataDir <- paste(homeDir, 'Dropbox/Projects/fc/fc/data/usable/extracted', sep='/')
dataFiles <- dir(dataDir, pattern='csv')
nSubj <- length(dataFiles) # number of subjects

# Going through all subjects' data:
df <- data.frame() # data frame that combines all subjects' data into a single ds
#curSubjN <- 6 #temp

for(curSubjN in 1:nSubj){
    # Loading the data;
    ds <- read.csv(paste(dataDir, dataFiles[curSubjN], sep='/'))
    # Shorter names for variables:
    colnames(ds) <- c('subjId', 'domEyeR', 'threshStHi', 'threshStLo', 'thresh', 'trialN', 'sentId',
                      'sentPx', 'congr', 'fam', 'locTop', 'cued', 'corr', 'broken', 'st')
    # Non-blank data set:
    cds <- ds[ds$sentId<31,]
    # Removing the outliers:
    outlLo <- cds$st>(mean(cds$st)-outT*sd(cds$st)) # binary for every row
    outlHi <- cds$st<(mean(cds$st)+outT*sd(cds$st))
    cds$outlNlo <- sum(!outlLo) # counting the number of outliers before removing
    cds$outlNhi <- sum(!outlHi)
    cds <- cds[outlLo,] # removing the outliers
    cds <- cds[outlHi,]
    cds <- cds[!is.na(cds$subjId),] # usually don't need this; remove NA rows
    # Normalized suppression times:
    cds$stNorm <- cds$st / mean(cds$st)    
    # Binding the subject ds to the common data frame:
    df <- rbind(df, cds)
}
# Prettying up the data frame:
df$subjId <- factor(df$subjId)
df$Familiarity[df$fam==1] <- 'Familiar\n(Upright)'
df$Familiarity[df$fam==0] <- 'Unfamiliar\n(Inverted)'
df$Congruency[df$congr==1] <- 'Congruent'
df$Congruency[df$congr==0] <- 'Incongruent'
df$Attention[df$cued==1] <- 'Cued'
df$Attention[df$cued==0] <- 'Uncued'
# Binning
df$bin <- 6
df$bin[df$trialN<500] <- 5
df$bin[df$trialN<400] <- 4
df$bin[df$trialN<300] <- 3
df$bin[df$trialN<200] <- 2
df$bin[df$trialN<100] <- 1
head(df)
```

# Quality control

## Summary stats per participant
```{r}
ddply(df, c('subjId'), summarise, outlNumLow = median(outlNlo), outlNumHigh = median(outlNhi),
      cuedCaught = sum(cued & corr), uncuedCaught = sum(!cued & corr))
```

## sts across trials
```{r, fig.height=3, fig.width=4.5}
for(curSubjN in 1:nSubj){
    curSubjId <- levels(df$subjId)[curSubjN]
    print(curSubjId)
    ss <- df[df$subjId==curSubjId,]
    p <- ggplot(data=ss, aes(x=trialN, y=st)) +  geom_line() + theme_bw() + ylim(.5,2) +
        labs(x='Trial Number', y='Suppression Time', title=paste('Participant', as.character(curSubjId))) + 
        theme(panel.grid.minor.x=element_blank(), panel.grid.minor.y=element_blank(),
              axis.text=element_text(size=8), axis.title=element_text(size=9),
              legend.text=element_text(size=8), legend.title=element_text(size=9),
              legend.key = element_blank(), #legend.margin=unit(-.04, 'in'),
              legend.background = element_rect(fill='transparent'))
    plot(p)
}
```

# Individual plots 

## Congruence X Familiarity X Cue
```{r, fig.height=3, fig.width=4.5}
for(curSubjN in 1:nSubj){
    curSubjId <- levels(df$subjId)[curSubjN]
    ss <- df[df$subjId==curSubjId,]
    p <- ggplot(data=ss, aes(x=factor(Familiarity), y=st, colour=factor(Congruency))) +  geom_boxplot() + 
        facet_grid(~Attention) + theme_bw() +
        labs(x='Familiarity', y='Suppression Time', colour='Congruency',
             title=paste('Participant', as.character(curSubjId))) + 
        theme(panel.grid.minor.x=element_blank(), panel.grid.minor.y=element_blank(),
              axis.text=element_text(size=8), axis.title=element_text(size=9),
              legend.text=element_text(size=8), legend.title=element_text(size=9),
              legend.key = element_blank(), #legend.margin=unit(-.04, 'in'),
              legend.background = element_rect(fill='transparent'))
    plot(p)
}
```

# Group plots

## Is cueing effective across participants?
```{r, fig.height=3, fig.width=9}
p <- ggplot(data=df, aes(x=Attention, y=st)) + geom_boxplot() + facet_grid(~subjId) + theme_bw() +
    labs(x='Attention effect X Subject', y='Suppression Time', colour='Attention',
         title='Effect of attentional cueing') +
    theme(panel.grid.minor.x=element_blank(), panel.grid.minor.y=element_blank(),
          axis.text=element_text(size=8), axis.title=element_text(size=9),
          legend.text=element_text(size=8), legend.title=element_text(size=9),
          legend.key = element_blank(), #legend.margin=unit(.0, 'in'),
          legend.background = element_rect(fill='transparent'))
plot(p)
```

## Is cueing effective across trials?
```{r, fig.height=3, fig.width=9}
p <- ggplot(data=df, aes(x=Attention, y=st)) + geom_boxplot() + facet_grid(~bin) + theme_bw() +
    labs(x='Attention effect X 100-trial bins', y='Suppression Time', colour='Attention',
         title='Effect of attentional cueing') +
    theme(panel.grid.minor.x=element_blank(), panel.grid.minor.y=element_blank(),
          axis.text=element_text(size=8), axis.title=element_text(size=9),
          legend.text=element_text(size=8), legend.title=element_text(size=9),
          legend.key = element_blank(), #legend.margin=unit(.0, 'in'),
          legend.background = element_rect(fill='transparent'))
plot(p)
```

## Congruence X Familiarity X Cue
```{r, fig.height=3, fig.width=4.5}
dfSum <- ddply(df, .(subjId, Attention, Familiarity, Congruency), summarise, 
               `Mean Normalized ST` = mean(stNorm, na.rm=T))
p <- ggplot(data=dfSum, aes(x=factor(Familiarity), y=`Mean Normalized ST`, 
                            colour=factor(Congruency))) + 
    geom_boxplot() +  facet_grid(~Attention) + theme_bw() +
    labs(x='Familiarity', y='Suppression Time', colour='Congruency',
         title='Congruence X Familiarty X Cue') + 
    theme(panel.grid.minor.x=element_blank(), panel.grid.minor.y=element_blank(),
          axis.text=element_text(size=8), axis.title=element_text(size=9),
          legend.text=element_text(size=8), legend.title=element_text(size=9),
          legend.key = element_blank(), #legend.margin=unit(-.04, 'in'),
          legend.background = element_rect(fill='transparent'))
plot(p)
```

```{r, fig.height=4, fig.width=8}
p <- ggplot(data=dfSum, aes(x=factor(Familiarity), y=`Mean Normalized ST`, 
                            group=factor(subjId), colour=factor(subjId))) + 
    geom_line() + facet_grid(~Attention*Congruency) + theme_bw() +
    labs(x='Familiarity', y='Suppression Time', colour='Congruency',
         title='Congruence X Familiarty X Cue') + 
    theme(panel.grid.minor.x=element_blank(), panel.grid.minor.y=element_blank(),
          axis.text=element_text(size=8), axis.title=element_text(size=9),
          legend.text=element_text(size=8), legend.title=element_text(size=9),
          legend.key = element_blank(), #legend.margin=unit(-.04, 'in'),
          legend.background = element_rect(fill='transparent'))
plot(p)
```

# Linear models
```{r}
# Centered data set:
```